services:
  - type: web
    name: youtube-analyzer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10

  - type: cron
    name: trending-cache-warmer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    schedule: "0 */3 * * *"  # 3시간마다 실행
    startCommand: python background_jobs.py warm-trending-cache