services:
  - type: web
    name: youtube-analyzer
    env: python
    plan: free
    # 빌드 명령어 수정
    buildCommand: pip install -r requirements.txt && flask db upgrade
    # 시작 명령어 수정
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
