"""Add saved_videos and categories tables

Revision ID: 17b88bd5f26c
Revises: 7131b24c7ecd
Create Date: 2025-08-01 00:50:32.575314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '17b88bd5f26c'
down_revision = '7131b24c7ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('oauth_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'uq_users_google_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f(
            'uq_users_username'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f('uq_users_username'), ['username'])
        batch_op.create_unique_constraint(
            batch_op.f('uq_users_google_id'), ['google_id'])

    op.create_table('oauth_tokens',
                    sa.Column('provider_user_id', sa.VARCHAR(
                        length=256), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('provider', sa.VARCHAR(
                        length=50), nullable=False),
                    sa.Column('created_at', sa.DATETIME(), nullable=False),
                    sa.Column('token', sqlite.JSON(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f(
                        'fk_oauth_tokens_user_id_users')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_oauth_tokens')),
                    sa.UniqueConstraint('provider_user_id', name=op.f(
                        'uq_oauth_tokens_provider_user_id'))
                    )
    # ### end Alembic commands ###
