"""Add category_id to saved_items table

Revision ID: 2862d1a8d786
Revises: 769a29563c87
Create Date: 2025-07-29 10:50:25.692958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2862d1a8d786'
down_revision = '769a29563c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_channel_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_channel_categories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_channel_categories'))
    )
    with op.batch_alter_table('saved_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_items', schema=None) as batch_op:
        batch_op.drop_column('category_id')

    op.drop_table('saved_channel_categories')
    # ### end Alembic commands ###
