"""Fix SearchHistory model and other minor issues

Revision ID: 332d8462b688
Revises: 20a0a72c0c89
Create Date: 2025-07-25 15:57:04.095499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332d8462b688'
down_revision = '20a0a72c0c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_term', sa.String(length=500), nullable=False))
        batch_op.drop_column('query')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_constraint('uq_users_google_id', type_='unique')

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('search_term')

    # ### end Alembic commands ###
