"""Add channel statistics tracking table

Revision ID: 47614d4e283d
Revises: ae398efcccd1
Create Date: 2025-07-24 23:51:16.879662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47614d4e283d'
down_revision = 'ae398efcccd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('channel_title', sa.String(length=500), nullable=False),
    sa.Column('custom_url', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('total_view_count', sa.BigInteger(), nullable=True),
    sa.Column('avg_views_per_video', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_stats'))
    )
    with op.batch_alter_table('channel_stats', schema=None) as batch_op:
        batch_op.create_index('idx_channel_recorded', ['channel_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_stats_channel_id'), ['channel_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('channel_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_stats_channel_id'))
        batch_op.drop_index('idx_channel_recorded')

    op.drop_table('channel_stats')
    # ### end Alembic commands ###
