"""Strengthen User-ApiKey relationship

Revision ID: 83640283b60c
Revises: dfce2f6455d8
Create Date: 2025-08-21 01:34:09.260923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83640283b60c'
down_revision = 'dfce2f6455d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_constraint('uq_users_google_id', type_='unique')

    # ### end Alembic commands ###
