"""Fix relationship between SavedItem and SavedChannelCategory

Revision ID: dfce2f6455d8
Revises: 17b88bd5f26c
Create Date: 2025-08-01 01:18:24.895974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfce2f6455d8'
down_revision = '17b88bd5f26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_items', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_saved_items_category_id_saved_channel_categories'), 'saved_channel_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_saved_items_category_id_saved_channel_categories'), type_='foreignkey')

    # ### end Alembic commands ###
