name: Warm Trending Cache

on:
  # [수정 또는 추가할 코드 시작]
  # 3시간마다 자동으로 실행되도록 스케줄 추가
  schedule:
    - cron: '0 */3 * * *' # UTC 기준, 매 3시간마다 0분에 실행
  
  # [유지] 코드를 푸시할 때도 테스트 목적으로 실행
  push:
    branches:
      - main
  
  # [추가] GitHub Actions 페이지에서 수동으로 실행할 수 있는 버튼 추가
  workflow_dispatch:
  # [수정 또는 추가할 코드 끝]

jobs:
  warm-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Warm the trending cache
        env:
          APP_URL: ${{ secrets.APP_URL || 'https://tube-analytics.com/' }}
          CACHE_WARM_TOKEN: ${{ secrets.CACHE_WARM_TOKEN }}
        run: |
          curl -X POST "${APP_URL}/api/warm-cache" \
            -H "Authorization: Bearer ${CACHE_WARM_TOKEN}" \
            -H "Content-Type: application/json"